# node.js.yml

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # Supported Node.js versions

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project (if needed)
      run: npm run build --if-present

    - name: Run unit tests
      run: npm test

    # --- Generate environment JSON for Newman with secrets ---
    - name: Create Newman environment file with secrets
      run: |
        cat > TrelloEnv.postman.json <<EOF
        {
          "id": "loader",
          "name": "Environment",
          "values": [
            {
              "key": "token",
              "value": "${{ secrets.token }}",
              "enabled": true
            },
            {
              "key": "key",
              "value": "${{ secrets.key }}",
              "enabled": true
            }
          ]
        }
        EOF

    - name: Run Newman tests via npm script
      run: npm run test
      env:
        token: ${{ secrets.token }}
        key: ${{ secrets.key }}