# node.js.yml

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # Supported Node.js versions

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build project (if needed)
      run: npm run build --if-present

    - name: Debug secrets
      run: |
        echo "NG_TOKEN: $NG_TOKEN"
        echo "NG_KEY: $NG_KEY"
      env:
        NG_TOKEN: ${{ secrets.token }}
        NG_KEY: ${{ secrets.key }}

    - name: Run Newman with Secrets
      run: npm run test
      env:
        NG_TOKEN: ${{ secrets.token }}
        NG_KEY: ${{ secrets.key }}


