name: Node.js CI with Newman Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    environment: TrelloAPI

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Newman tests
        env:
          TOKEN: ${{ secrets.TOKEN }}
          KEY: ${{ secrets.KEY }}
        run: newman run TrelloAPI.postman.json \ --env-var "token=${{secrets.TOKEN}}" \ --env-var "key=${{secrets.KEY}}"
      
