name: Node.js CI with Newman Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Debug secrets - see if secrets are loaded
        run: |
          echo "Checking environment variables..."
          echo "TOKEN is set: $TOKEN"
          echo "KEY is set: $KEY"

      - name: Show secret lengths (don't reveal secrets!)
        run: |
          echo "TOKEN length: ${#TOKEN}"
          echo "KEY length: ${#KEY}"

      - name: Run Newman tests
        run: npm run test
        env:
          TOKEN: ${{ secrets.TOKEN }}
          KEY: ${{ secrets.KEY }}